name: CI Test 

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm
    - name: setup yarn
      run: yarn install
    - name: 
      run: yarn run test
